<?= $this->doctype() . PHP_EOL; ?>
<html>
    <head>
        <?php
            $this->headTitle('Mon appli')->setSeparator(' - ');
            echo $this->headTitle() . PHP_EOL;
            
            $this->headMeta()->appendName('viewport', 'width=device-width initial-scale=1');
            
            echo $this->headMeta() . PHP_EOL;
            
            $this->headLink()->prependStylesheet("/assets/bootstrap/dist/css/bootstrap.min.css");
            $this->headLink()->prependStylesheet("/assets/bootstrap/dist/css/bootstrap-theme.min.css");
            $this->headLink()->appendStylesheet("//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css");
            $this->headLink()->appendStylesheet("/css/main.css");
            
            echo $this->headLink() . PHP_EOL; 
            
            echo $this->headStyle() . PHP_EOL;
            
            echo $this->headScript() . PHP_EOL;
        ?>
    </head>
    <body>

    <?= $this->partial('partials/menu.phtml');?>
	<div class="container">
	  
	   <div class="header">
         <h3 class="text-muted">Project name</h3>
       </div>
      <?= $this->partial('partials/priorityMessages.phtml', array('priorityMessages'=> $this->priorityMessenger())); ?>
      <?= $this->layout()->content; ?>
      <footer class="footer">
        <p>© Company 2014</p>
      </footer>
	</div>
	
	   <?php 
	    $this->inlineScript()->prependFile("/assets/bootstrap/dist/js/bootstrap.min.js");
	    $this->inlineScript()->prependFile("/assets/jquery/dist/jquery.min.js");
	    
	    echo $this->inlineScript() . PHP_EOL; ?> 


	</body>
</html>