<tr>
	<td><?= $this->id?></td>
	<td><a href="<?= $this->url?>" target="_blank"><?= $this->title?></a></td>
	<td><?= substr($this->description, 0, 50) . '...'?></td>
	<td><a href="<?= $this->url(array('id' => $this->id), 'webEdit')?>" class="btn btn-xs btn-success">
			<span class="glyphicon glyphicon-pencil"></span> Editer</a> 
		<a href="<?= $this->url(array('id' => $this->id), 'webDelete')?>" class="btn btn-xs btn-danger">
			<span class="glyphicon glyphicon-trash"></span>Supprimer</a></td>
</tr>