<?php 
	$this->headLink()->appendStylesheet("./assets/datatables/media/css/jquery.dataTables.min.css");
	//$this->inlineScript()->appendFile("./assets/datatables/media/js/jquery.js");
	$this->inlineScript()->appendFile("./assets/datatables/media/js/jquery.dataTables.min.js");
?>

<?php if (0 === count($this->skills)) { ?>
<p class="lead">Aucune Compétence</p>
<hr>
<?php } else { ?>
<h2>Liste des compétences</h2>
<hr>
<table id="skills" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>Catégorie</th>
            <th>Description</th>
            <th>Niveau</th>
            <th>Expérience</th>
            <th>Action</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th>Catégorie</th>
            <th>Description</th>
            <th>Niveau</th>
            <th>Expérience</th>
            <th>Action</th>
        </tr>
    </tfoot>    
    <tbody>
<?= 		$this->partialLoop('skill/partials/item-index.phtml', $this->skills)?>
    </tbody>
</table>

<?php 		$this->inlineScript()->captureStart() ?>
$(document).ready(function() {
	$('#skills').dataTable();
	$('#skills span.label').click(function(){
		  var div = $(this).parent().find('span:first-child');
		  div.toggle();
		  if (div.is(":visible")){
			    $(this).text('LESS');
		  } else {
			    $(this).text('MORE');
		  }    
	});

	$('#skills div span.label').click(function(){
		  $(this).parent().hide();
		  $('.more + div').css('display', 'none');
		  $('.more').css('display', 'inline-block');
	});	
});
<?php 		$this->inlineScript()->captureEnd();
	   } ?>