<?php 
$this->headLink()->appendStylesheet("/assets/datatables/media/css/jquery.dataTables.min.css");
$this->inlineScript()->appendFile("/assets/datatables/media/js/jquery.js");
//$this->inlineScript()->appendFile("/assets/jquery/dist/jquery.min.js");
$this->inlineScript()->appendFile("/assets/datatables/media/js/jquery.dataTables.min.js");
?>
<h2>Liste des compétences</h2>
<hr />
<a href="<?= $this->url(array(), 'skillAdd')?>" class="btn btn-xs btn-success"><span class="glyphicon glyphicon-plus"></span> Nouvelle compétence</a>
<hr />

<?php //echo(count($this->messages) ? '<p>' . implode('<br />',$this->messages) . '</p>' : ''); ?>

<table id="skills" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
    <?php // générer automatiquement les noms de colonnes
        /*
     id
     catégorie
     description 
     niveau
     expérience
     */?>
        <tr>
            <th>Id</th>
            <th>Catégorie</th>
            <th>Description</th>
            <th>Niveau</th>
            <th>Expérience</th>
            <th>Action</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th>Id</th>
            <th>Catégorie</th>
            <th>Description</th>
            <th>Niveau</th>
            <th>Expérience</th>
            <th>Action</th>
        </tr>
    </tfoot>    
    <tbody>
    <?php foreach ($this->skills as $skill) : ?>
        <tr>
            <td><?= $skill->getId()?></td>
            <td><?= $skill->getCategory()->getName()?></td>
            <td style="width:200px;"><?= $this->moreLess($skill->getDescription())?></td>
            <td><?= $skill->getLevel()?></td>
            <td><?= $skill->getExperience()?></td>
            <td><a href="<?= $this->url(array('id' => $skill->getId()), 'skillEdit')?>" class="btn btn-xs btn-success"><span class="glyphicon glyphicon-pencil"></span> Editer</a>
                <a href="<?= $this->url(array('id' => $skill->getId()), 'skillDelete')?>" class="btn btn-xs btn-danger"><span class="glyphicon glyphicon-trash"></span> Supprimer</a></td>
        </tr> 
    <?php endforeach;?>
    </tbody>
</table>
    
<script>
<?php $this->inlineScript()->captureStart() ?>
$(document).ready(function() {
	$('#skills').dataTable();
	$('#skills span.label').click(function(){
		  var div = $(this).parent().find('span:first-child');
		  div.toggle();
		  if (div.is(":visible")){
			    $(this).text('LESS');
		  } else {
			    $(this).text('MORE');
		  }    
	});

	$('#skills div span.label').click(function(){
		  $(this).parent().hide();
		  $('.more + div').css('display', 'none');
		  $('.more').css('display', 'inline-block');
	});	
});
<?php $this->inlineScript()->captureEnd() ?>
</script>